"""Seed data for CyberHead Academy — courses, modules, lessons, testimonials."""

COURSE_THUMBS = {
    "eh": "https://images.unsplash.com/photo-1614064548237-096f735f344f?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "webapp": "https://images.unsplash.com/photo-1593720219128-218edc93bdc0?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "api": "https://images.unsplash.com/photo-1610989001873-03968eed0f08?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "bugbounty": "https://images.unsplash.com/photo-1618060932014-4deda4932554?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "vapt": "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "linux": "https://images.unsplash.com/photo-1542255034-288a8a58a2a6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "osint": "https://images.unsplash.com/photo-1510915228340-29c85a43dcfe?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
    "webtest": "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200",
}

INSTRUCTORS = {
    "arjun": {"name": "Arjun Mehta", "avatar": "https://images.unsplash.com/photo-1560250097-0b93528c311a?crop=entropy&cs=srgb&fm=jpg&q=85&w=256", "title": "Lead Offensive Security Engineer"},
    "priya": {"name": "Priya Nair", "avatar": "https://images.unsplash.com/photo-1675869940341-d495d49010b5?crop=entropy&cs=srgb&fm=jpg&q=85&w=256", "title": "Principal Application Security Researcher"},
    "daniel": {"name": "Daniel Cortez", "avatar": "https://images.unsplash.com/photo-1620825937374-87fc7d6bddc2?crop=entropy&cs=srgb&fm=jpg&q=85&w=256", "title": "Senior Penetration Tester"},
}


def _mods(pairs):
    mods = []
    for i, (title, lessons) in enumerate(pairs, start=1):
        mods.append({
            "order": i,
            "title": title,
            "lessons": [{"order": j + 1, "title": l, "duration_min": 12 + (j * 3) % 20} for j, l in enumerate(lessons)],
        })
    return mods


COURSES = [
    {
        "slug": "complete-ethical-hacking-bug-bounty",
        "title": "Complete Ethical Hacking & Bug Bounty",
        "short": "Go from zero to a job-ready ethical hacker with hands-on labs covering reconnaissance, exploitation and reporting.",
        "description": "A comprehensive, practical path into offensive security. You'll build a professional testing methodology, learn to find and responsibly disclose real vulnerabilities, and assemble a bug bounty workflow used by top hunters.",
        "instructor": "arjun",
        "difficulty": "Beginner",
        "category": "Bug Bounty",
        "duration_hours": 42,
        "price": 129.0,
        "rating": 4.9,
        "students": 18420,
        "thumb": COURSE_THUMBS["eh"],
        "featured": True,
        "modules": _mods([
            ("Foundations of Ethical Hacking", ["The hacker mindset & legal scope", "Building your lab safely", "Networking essentials refresher"]),
            ("Reconnaissance", ["Passive recon & OSINT", "Active scanning with Nmap", "Subdomain enumeration"]),
            ("Web Exploitation", ["Mapping the attack surface", "Common web vulnerabilities", "Chaining findings"]),
            ("Reporting & Disclosure", ["Writing a great report", "CVSS scoring", "Coordinated disclosure"]),
        ]),
    },
    {
        "slug": "web-application-security",
        "title": "Web Application Security",
        "short": "Master the OWASP Top 10 and defend modern web apps against real-world attacks.",
        "description": "Understand how web applications break and how to secure them. Deep dives into injection, authentication, authorization, and API security with defensive engineering patterns you can ship.",
        "instructor": "priya",
        "difficulty": "Intermediate",
        "category": "Web Security",
        "duration_hours": 36,
        "price": 149.0,
        "rating": 4.8,
        "students": 12980,
        "thumb": COURSE_THUMBS["webapp"],
        "featured": True,
        "modules": _mods([
            ("Introduction to Web Security", ["Threat modeling basics", "The browser security model"]),
            ("HTTP & HTTPS", ["Anatomy of an HTTP request", "TLS, cookies & headers"]),
            ("Authentication", ["Password storage done right", "Session vs JWT", "MFA patterns"]),
            ("Authorization", ["RBAC & ABAC", "Broken access control", "IDOR prevention"]),
            ("Injection Attacks", ["SQL injection & parameterization", "Command injection defense"]),
            ("XSS", ["Reflected, stored & DOM XSS", "Content Security Policy"]),
            ("API Security", ["Rate limiting & throttling", "Input validation at the boundary"]),
        ]),
    },
    {
        "slug": "api-security-fundamentals",
        "title": "API Security Fundamentals",
        "short": "Secure REST and GraphQL APIs against the OWASP API Security Top 10.",
        "description": "APIs are the backbone of modern software and the biggest attack surface. Learn authentication, authorization, rate limiting, schema validation and abuse prevention for production APIs.",
        "instructor": "priya",
        "difficulty": "Intermediate",
        "category": "Web Security",
        "duration_hours": 24,
        "price": 119.0,
        "rating": 4.7,
        "students": 8640,
        "thumb": COURSE_THUMBS["api"],
        "featured": False,
        "modules": _mods([
            ("API Threat Landscape", ["OWASP API Top 10", "Common misconfigurations"]),
            ("AuthN & AuthZ", ["OAuth2 & OIDC", "Scopes & least privilege"]),
            ("Abuse Prevention", ["Rate limiting strategies", "Bot & scraping defense"]),
            ("Validation", ["Schema validation", "Mass assignment protection"]),
        ]),
    },
    {
        "slug": "bug-bounty-hunting",
        "title": "Bug Bounty Hunting",
        "short": "A hunter's playbook: recon automation, high-impact bug classes and clean reports.",
        "description": "Turn recon into rewards. This course focuses on repeatable workflows, automation, and the bug classes that consistently pay — access control, SSRF, and business logic flaws.",
        "instructor": "arjun",
        "difficulty": "Advanced",
        "category": "Bug Bounty",
        "duration_hours": 30,
        "price": 159.0,
        "rating": 4.9,
        "students": 10230,
        "thumb": COURSE_THUMBS["bugbounty"],
        "featured": False,
        "modules": _mods([
            ("Recon Automation", ["Building a recon pipeline", "Continuous monitoring"]),
            ("High-Impact Bugs", ["Access control flaws", "SSRF deep dive", "Business logic abuse"]),
            ("Programs & Reports", ["Choosing programs", "Report writing that gets paid"]),
        ]),
    },
    {
        "slug": "practical-vapt",
        "title": "Practical VAPT",
        "short": "Run end-to-end Vulnerability Assessment & Penetration Tests like a consultant.",
        "description": "A consultant-grade methodology for VAPT engagements — scoping, assessment, exploitation, and executive reporting — built around realistic corporate environments.",
        "instructor": "daniel",
        "difficulty": "Advanced",
        "category": "Pentesting",
        "duration_hours": 40,
        "price": 179.0,
        "rating": 4.8,
        "students": 7110,
        "thumb": COURSE_THUMBS["vapt"],
        "featured": False,
        "modules": _mods([
            ("Engagement Setup", ["Scoping & rules of engagement", "Assessment tooling"]),
            ("Assessment", ["Vulnerability scanning", "Manual verification"]),
            ("Exploitation", ["Safe exploitation", "Privilege escalation"]),
            ("Reporting", ["Executive summaries", "Remediation roadmaps"]),
        ]),
    },
    {
        "slug": "linux-for-cybersecurity",
        "title": "Linux for Cybersecurity",
        "short": "The Linux command-line skills every security professional needs.",
        "description": "Become fluent on the command line. Filesystem, permissions, networking, scripting and hardening — the practical Linux foundation for every security role.",
        "instructor": "daniel",
        "difficulty": "Beginner",
        "category": "Pentesting",
        "duration_hours": 20,
        "price": 89.0,
        "rating": 4.7,
        "students": 15600,
        "thumb": COURSE_THUMBS["linux"],
        "featured": False,
        "modules": _mods([
            ("Command Line Basics", ["Navigation & files", "Permissions & users"]),
            ("Networking", ["Interfaces & routing", "Packet tools"]),
            ("Scripting", ["Bash fundamentals", "Automation for pentesters"]),
            ("Hardening", ["Service hardening", "Logging & auditing"]),
        ]),
    },
    {
        "slug": "osint-fundamentals",
        "title": "OSINT Fundamentals",
        "short": "Gather and analyze open-source intelligence ethically and effectively.",
        "description": "Master open-source intelligence techniques used in reconnaissance and investigations — footprinting, people & infrastructure research, and responsible practice.",
        "instructor": "priya",
        "difficulty": "Beginner",
        "category": "Web Security",
        "duration_hours": 18,
        "price": 79.0,
        "rating": 4.6,
        "students": 9040,
        "thumb": COURSE_THUMBS["osint"],
        "featured": False,
        "modules": _mods([
            ("OSINT Foundations", ["The intelligence cycle", "Operational security"]),
            ("Infrastructure Recon", ["Domain & DNS research", "Certificate transparency"]),
            ("People & Orgs", ["Footprinting responsibly", "Verifying sources"]),
        ]),
    },
    {
        "slug": "web-security-testing",
        "title": "Web Security Testing",
        "short": "Hands-on testing techniques for finding flaws in modern web apps.",
        "description": "A lab-driven course on testing methodology — proxying traffic, fuzzing, and validating findings across authentication, injection, and access-control surfaces.",
        "instructor": "arjun",
        "difficulty": "Intermediate",
        "category": "WAF & Defense",
        "duration_hours": 28,
        "price": 139.0,
        "rating": 4.8,
        "students": 8320,
        "thumb": COURSE_THUMBS["webtest"],
        "featured": False,
        "modules": _mods([
            ("Testing Setup", ["Intercepting proxies", "Scoping a test"]),
            ("Discovery", ["Content discovery", "Parameter fuzzing"]),
            ("Validation", ["Confirming findings", "Reducing false positives"]),
            ("Defense in Depth", ["WAF concepts", "Virtual patching"]),
        ]),
    },
]

TESTIMONIALS = [
    {"name": "Rahul Verma", "role": "Security Analyst @ Fintech", "quote": "The labs feel like real engagements. I landed my first SOC role two months after finishing the Web Application Security path.", "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=srgb&fm=jpg&q=85&w=128"},
    {"name": "Meera Iyer", "role": "Bug Bounty Hunter", "quote": "CyberHead's recon workflow paid for itself with my first valid report. Practical, no fluff, and constantly updated.", "avatar": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?crop=entropy&cs=srgb&fm=jpg&q=85&w=128"},
    {"name": "Kenji Tanaka", "role": "Pentester @ Consultancy", "quote": "The VAPT course mirrors exactly how we run client engagements. My reports have never been cleaner.", "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=srgb&fm=jpg&q=85&w=128"},
]

FAQS = [
    {"q": "Do I need prior experience to start?", "a": "No. Beginner tracks like Linux for Cybersecurity and OSINT Fundamentals assume zero background and build up step by step."},
    {"q": "Are the labs safe and legal to practice?", "a": "Yes. Every lab runs in a controlled, sandboxed environment. You never attack systems you don't own or aren't authorized to test."},
    {"q": "Do you cover WAF and defense, not just attacks?", "a": "Absolutely. Our Security Lab demonstrates how a SafeLine WAF inspects and handles suspicious traffic, so you learn both offense and defense."},
    {"q": "Will I get a certificate?", "a": "You earn a shareable completion certificate and a Security Learning Score that reflects your hands-on progress."},
    {"q": "How often is content updated?", "a": "Modules are reviewed quarterly and updated whenever new vulnerability classes or tooling become relevant."},
]
